export type Platform = {
  id: string;
  name: string;
  slug: string;
  category: string;
  difficulty: "easy" | "medium" | "hard";
  estimatedTime: string;
  description: string;
  guideUrl?: string;
};

export const platforms: Platform[] = [
  // Sosiale medier
  {
    id: "facebook",
    name: "Facebook",
    slug: "facebook",
    category: "Sosiale medier",
    difficulty: "medium",
    estimatedTime: "30 dager",
    description: "Slett din Facebook-konto permanent eller deaktiver midlertidig.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-facebook",
  },
  {
    id: "instagram",
    name: "Instagram",
    slug: "instagram",
    category: "Sosiale medier",
    difficulty: "medium",
    estimatedTime: "30 dager",
    description: "Slett din Instagram-profil og alle tilknyttede data.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-instagram",
  },
  {
    id: "tiktok",
    name: "TikTok",
    slug: "tiktok",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "7 dager",
    description: "Deaktiver eller slett din TikTok-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-tiktok",
  },
  {
    id: "twitter",
    name: "X (Twitter)",
    slug: "twitter",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "30 dager",
    description: "Slett din X-konto og alle tweets.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-x-twitter",
  },
  {
    id: "snapchat",
    name: "Snapchat",
    slug: "snapchat",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "30 dager",
    description: "Slett din Snapchat-konto og alle minner.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-snapchat",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    slug: "linkedin",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din LinkedIn-profil og profesjonelle data.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-linkedin",
  },
  {
    id: "pinterest",
    name: "Pinterest",
    slug: "pinterest",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "14 dager",
    description: "Slett din Pinterest-konto og alle pins.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-kontoen-din-pa-pinterest",
  },
  {
    id: "tumblr",
    name: "Tumblr",
    slug: "tumblr",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Tumblr-blogg og konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-tumblr",
  },
  {
    id: "discord",
    name: "Discord",
    slug: "discord",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "14 dager",
    description: "Slett din Discord-konto og serverdata.",
  },
  {
    id: "gaysir",
    name: "Gaysir",
    slug: "gaysir",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Gaysir-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-kan-du-slette-deg-fra-gaysir",
  },
  {
    id: "vsco",
    name: "VSCO",
    slug: "vsco",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din VSCO-profil og bilder.",
  },
  {
    id: "hemmelig",
    name: "Hemmelig.com",
    slug: "hemmelig",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din profil fra Hemmelig.com.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-en-profil-fra-hemmelig-com",
  },
  {
    id: "kik",
    name: "Kik",
    slug: "kik",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Kik-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-kik",
  },
  {
    id: "meetme",
    name: "MeetMe",
    slug: "meetme",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din MeetMe-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-kan-du-slette-deg-fra-meetme",
  },
  {
    id: "disqus",
    name: "Disqus",
    slug: "disqus",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Disqus-profil og kommentarer.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-disqus-profilen-din",
  },

  // Dating
  {
    id: "tinder",
    name: "Tinder",
    slug: "tinder",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Tinder-profil og alle matcher.",
  },
  {
    id: "badoo",
    name: "Badoo",
    slug: "badoo",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Badoo-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-badoo",
  },
  {
    id: "match",
    name: "Match.com",
    slug: "match",
    category: "Dating",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din Match.com-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-match-com",
  },
  {
    id: "sukker",
    name: "Sukker.no",
    slug: "sukker",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Sukker.no datingprofil.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-sukker-no",
  },
  {
    id: "moteplassen",
    name: "Moteplassen",
    slug: "moteplassen",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din profil fra Moteplassen.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-moteplassen",
  },
  {
    id: "c-date",
    name: "C-date",
    slug: "c-date",
    category: "Dating",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din C-date konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-c-date",
  },
  {
    id: "be2",
    name: "Be2",
    slug: "be2",
    category: "Dating",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din Be2-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-be2-no",
  },
  {
    id: "singles50",
    name: "Singles50",
    slug: "singles50",
    category: "Dating",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din Singles50-konto.",
  },
  {
    id: "zoosk",
    name: "Zoosk",
    slug: "zoosk",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Deaktiver din Zoosk-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-zoosk",
  },
  {
    id: "twoo",
    name: "Twoo",
    slug: "twoo",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Steng din Twoo-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-twoo",
  },
  {
    id: "flirt",
    name: "Flirt.com",
    slug: "flirt",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Flirt.com-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-flirt-com",
  },
  {
    id: "flirtfair",
    name: "Flirtfair",
    slug: "flirtfair",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Flirtfair-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-kan-du-slette-deg-fra-flirtfair",
  },
  {
    id: "benaughty",
    name: "BeNaughty",
    slug: "benaughty",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din BeNaughty-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-benaughty-no",
  },
  {
    id: "naughtybook",
    name: "Naughtybook",
    slug: "naughtybook",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Naughtybook-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-naughtybook",
  },
  {
    id: "rampetepiker",
    name: "Rampetepiker",
    slug: "rampetepiker",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din profil fra Rampetepiker.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-rampetepiker-no",
  },
  {
    id: "sidesprang",
    name: "Sidesprang",
    slug: "sidesprang",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Sidesprang-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-sidesprang-no",
  },
  {
    id: "casualpartners",
    name: "Casualpartners",
    slug: "casualpartners",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Casualpartners-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-casualpartners",
  },
  {
    id: "badults",
    name: "Badults",
    slug: "badults",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Badults-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-badults",
  },
  {
    id: "treffeldredamer",
    name: "TreffEldreDamer",
    slug: "treffeldredamer",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din TreffEldreDamer-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-treffeldredamer",
  },

  // Teknologi / E-post
  {
    id: "google",
    name: "Google",
    slug: "google",
    category: "Teknologi",
    difficulty: "hard",
    estimatedTime: "Umiddelbart",
    description: "Slett din Google-konto inkludert Gmail, YouTube, Drive.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-en-google-konto",
  },
  {
    id: "microsoft",
    name: "Microsoft / Outlook / Hotmail",
    slug: "microsoft",
    category: "Teknologi",
    difficulty: "medium",
    estimatedTime: "60 dager",
    description: "Slett din Microsoft-konto inkludert Outlook, Hotmail, Skype.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-din-microsoft-konto",
  },
  {
    id: "yahoo",
    name: "Yahoo",
    slug: "yahoo",
    category: "Teknologi",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Avslutt din Yahoo-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-kan-du-slette-deg-fra-yahoo",
  },
  {
    id: "samsung",
    name: "Samsung",
    slug: "samsung",
    category: "Teknologi",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Samsung-konto permanent.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-din-samsung-konto",
  },
  {
    id: "skype",
    name: "Skype",
    slug: "skype",
    category: "Teknologi",
    difficulty: "medium",
    estimatedTime: "60 dager",
    description: "Slett din Skype-konto (krever Microsoft-sletting).",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-skype",
  },
  {
    id: "digipost",
    name: "Digipost",
    slug: "digipost",
    category: "Teknologi",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Deaktiver din Digipost digital postkasse.",
    guideUrl: "https://slettmeg.no/veiledninger/deaktiver-digipost",
  },

  // Streaming / Video
  {
    id: "youtube",
    name: "YouTube",
    slug: "youtube",
    category: "Streaming",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din YouTube-kanal og videoer.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-youtube",
  },
  {
    id: "spotify",
    name: "Spotify",
    slug: "spotify",
    category: "Streaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Spotify-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-spotify",
  },
  {
    id: "flickr",
    name: "Flickr",
    slug: "flickr",
    category: "Streaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Flickr-konto og bilder.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-flickr",
  },
  {
    id: "zoomerang",
    name: "Zoomerang",
    slug: "zoomerang",
    category: "Streaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Zoomerang-konto.",
  },

  // Blogging
  {
    id: "blogger",
    name: "Blogger.com",
    slug: "blogger",
    category: "Blogging",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din blogg fra Blogger.com.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-blogger-com",
  },
  {
    id: "wordpress",
    name: "WordPress.com",
    slug: "wordpress",
    category: "Blogging",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din WordPress-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-wordpress-com",
  },
  {
    id: "bloglovin",
    name: "Bloglovin",
    slug: "bloglovin",
    category: "Blogging",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Bloglovin-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-bloglovin",
  },
  {
    id: "myspace",
    name: "Myspace",
    slug: "myspace",
    category: "Blogging",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din Myspace-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-myspace",
  },

  // Gaming
  {
    id: "roblox",
    name: "Roblox",
    slug: "roblox",
    category: "Gaming",
    difficulty: "medium",
    estimatedTime: "30 dager",
    description: "Slett din Roblox-konto.",
  },

  // Andre tjenester
  {
    id: "myheritage",
    name: "MyHeritage",
    slug: "myheritage",
    category: "Andre",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din MyHeritage-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-myheritage",
  },
  {
    id: "underskrift",
    name: "Underskrift.no",
    slug: "underskrift",
    category: "Andre",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett underskrift fra underskrift.no.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-en-underskrift-fra-underskrift-no",
  },

  // Sokemotorer
  {
    id: "google-search",
    name: "Google Sok",
    slug: "google-search",
    category: "Sokemotorer",
    difficulty: "medium",
    estimatedTime: "Varierer",
    description: "Skjul eller fjern treff fra Google-sok.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-kan-du-skjule-treff-fra-google",
  },
  {
    id: "bing-search",
    name: "Bing Sok",
    slug: "bing-search",
    category: "Sokemotorer",
    difficulty: "medium",
    estimatedTime: "Varierer",
    description: "Skjul eller fjern treff fra Bing-sok.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-kan-du-skjule-treff-fra-bing",
  },

  // Nummeropplysning
  {
    id: "nettkatalogene",
    name: "Nettkatalogene",
    slug: "nettkatalogene",
    category: "Nummeropplysning",
    difficulty: "easy",
    estimatedTime: "Varierer",
    description: "Slett deg fra nummeropplysningene.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-nettkatalogene",
  },

  // Finans / Krypto
  {
    id: "etoro",
    name: "eToro",
    slug: "etoro",
    category: "Finans",
    difficulty: "medium",
    estimatedTime: "30 dager",
    description: "Slett din eToro-konto og handelsdata.",
  },
  {
    id: "kucoin",
    name: "KuCoin",
    slug: "kucoin",
    category: "Finans",
    difficulty: "medium",
    estimatedTime: "Varierer",
    description: "Slett din KuCoin kryptokonto.",
  },
  {
    id: "cryptocom",
    name: "Crypto.com",
    slug: "cryptocom",
    category: "Finans",
    difficulty: "medium",
    estimatedTime: "Varierer",
    description: "Slett din Crypto.com-konto.",
  },
  {
    id: "binance",
    name: "Binance",
    slug: "binance",
    category: "Finans",
    difficulty: "medium",
    estimatedTime: "Varierer",
    description: "Slett din Binance kryptokonto.",
  },
  {
    id: "coinbase",
    name: "Coinbase",
    slug: "coinbase",
    category: "Finans",
    difficulty: "medium",
    estimatedTime: "Varierer",
    description: "Slett din Coinbase-konto.",
  },

  // Meldingstjenester
  {
    id: "telegram",
    name: "Telegram",
    slug: "telegram",
    category: "Meldingstjenester",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Telegram-konto og meldinger.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-telegram",
  },
  {
    id: "wechat",
    name: "WeChat",
    slug: "wechat",
    category: "Meldingstjenester",
    difficulty: "medium",
    estimatedTime: "60 dager",
    description: "Slett din WeChat-konto.",
  },
  {
    id: "signal",
    name: "Signal",
    slug: "signal",
    category: "Meldingstjenester",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Signal-konto.",
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    slug: "whatsapp",
    category: "Meldingstjenester",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din WhatsApp-konto og meldinger.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-whatsapp",
  },
  {
    id: "messenger",
    name: "Messenger",
    slug: "messenger",
    category: "Meldingstjenester",
    difficulty: "medium",
    estimatedTime: "30 dager",
    description: "Slett din Messenger-konto (krever Facebook).",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-facebook-messenger",
  },

  // Flere sosiale medier
  {
    id: "reddit",
    name: "Reddit",
    slug: "reddit",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Reddit-konto og alle innlegg.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-reddit",
  },
  {
    id: "quora",
    name: "Quora",
    slug: "quora",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "14 dager",
    description: "Slett din Quora-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-quora",
  },
  {
    id: "threads",
    name: "Threads",
    slug: "threads",
    category: "Sosiale medier",
    difficulty: "medium",
    estimatedTime: "30 dager",
    description: "Slett din Threads-profil (knyttet til Instagram).",
  },
  {
    id: "ask-fm",
    name: "Ask.fm",
    slug: "ask-fm",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Ask.fm-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-ask-fm",
  },
  {
    id: "jodel",
    name: "Jodel",
    slug: "jodel",
    category: "Sosiale medier",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Jodel-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-jodel",
  },

  // E-handel
  {
    id: "amazon",
    name: "Amazon",
    slug: "amazon",
    category: "E-handel",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din Amazon-konto og kjopshistorikk.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-din-amazon-konto",
  },
  {
    id: "ebay",
    name: "eBay",
    slug: "ebay",
    category: "E-handel",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din eBay-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-ebay",
  },
  {
    id: "wish",
    name: "Wish",
    slug: "wish",
    category: "E-handel",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Wish-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-wish",
  },
  {
    id: "aliexpress",
    name: "AliExpress",
    slug: "aliexpress",
    category: "E-handel",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din AliExpress-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-kan-du-slette-deg-fra-aliexpress",
  },
  {
    id: "finn",
    name: "Finn.no",
    slug: "finn",
    category: "E-handel",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Finn.no-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slett-deg-fra-finn-no",
  },

  // Apple
  {
    id: "apple",
    name: "Apple ID",
    slug: "apple",
    category: "Teknologi",
    difficulty: "hard",
    estimatedTime: "7 dager",
    description: "Slett din Apple ID og alle tilknyttede tjenester.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-din-apple-id",
  },

  // Gaming
  {
    id: "steam",
    name: "Steam",
    slug: "steam",
    category: "Gaming",
    difficulty: "medium",
    estimatedTime: "30 dager",
    description: "Slett din Steam-konto og spillbibliotek.",
  },
  {
    id: "epic-games",
    name: "Epic Games",
    slug: "epic-games",
    category: "Gaming",
    difficulty: "medium",
    estimatedTime: "14 dager",
    description: "Slett din Epic Games-konto.",
  },
  {
    id: "playstation",
    name: "PlayStation Network",
    slug: "playstation",
    category: "Gaming",
    difficulty: "medium",
    estimatedTime: "Umiddelbart",
    description: "Slett din PlayStation Network-konto.",
  },
  {
    id: "xbox",
    name: "Xbox Live",
    slug: "xbox",
    category: "Gaming",
    difficulty: "medium",
    estimatedTime: "60 dager",
    description: "Slett din Xbox Live-konto (krever Microsoft-sletting).",
  },
  {
    id: "twitch",
    name: "Twitch",
    slug: "twitch",
    category: "Gaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Twitch-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-twitch",
  },

  // Streaming
  {
    id: "netflix",
    name: "Netflix",
    slug: "netflix",
    category: "Streaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Netflix-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-netflix",
  },
  {
    id: "hbo-max",
    name: "HBO Max",
    slug: "hbo-max",
    category: "Streaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din HBO Max-konto.",
  },
  {
    id: "disney-plus",
    name: "Disney+",
    slug: "disney-plus",
    category: "Streaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Disney+-konto.",
  },
  {
    id: "viaplay",
    name: "Viaplay",
    slug: "viaplay",
    category: "Streaming",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Viaplay-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-viaplay",
  },

  // Skytjenester
  {
    id: "dropbox",
    name: "Dropbox",
    slug: "dropbox",
    category: "Skytjenester",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Dropbox-konto og filer.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-dropbox",
  },
  {
    id: "icloud",
    name: "iCloud",
    slug: "icloud",
    category: "Skytjenester",
    difficulty: "hard",
    estimatedTime: "7 dager",
    description: "Slett din iCloud-konto (krever Apple ID-sletting).",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    slug: "onedrive",
    category: "Skytjenester",
    difficulty: "medium",
    estimatedTime: "60 dager",
    description: "Slett din OneDrive-konto (krever Microsoft-sletting).",
  },

  // Jobbtjenester
  {
    id: "indeed",
    name: "Indeed",
    slug: "indeed",
    category: "Jobbtjenester",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Indeed-konto og CV.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-indeed",
  },
  {
    id: "glassdoor",
    name: "Glassdoor",
    slug: "glassdoor",
    category: "Jobbtjenester",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Glassdoor-konto.",
  },

  // Transport
  {
    id: "uber",
    name: "Uber",
    slug: "uber",
    category: "Transport",
    difficulty: "easy",
    estimatedTime: "30 dager",
    description: "Slett din Uber-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-uber",
  },
  {
    id: "bolt",
    name: "Bolt",
    slug: "bolt",
    category: "Transport",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Bolt-konto.",
  },

  // Mat / Levering
  {
    id: "foodora",
    name: "Foodora",
    slug: "foodora",
    category: "Matlevering",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Foodora-konto.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-foodora",
  },
  {
    id: "wolt",
    name: "Wolt",
    slug: "wolt",
    category: "Matlevering",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Wolt-konto.",
  },

  // Flere dating
  {
    id: "bumble",
    name: "Bumble",
    slug: "bumble",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Bumble-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-bumble",
  },
  {
    id: "hinge",
    name: "Hinge",
    slug: "hinge",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Hinge-profil.",
  },
  {
    id: "okcupid",
    name: "OkCupid",
    slug: "okcupid",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din OkCupid-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-okcupid",
  },
  {
    id: "happn",
    name: "Happn",
    slug: "happn",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Happn-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-happn",
  },
  {
    id: "grindr",
    name: "Grindr",
    slug: "grindr",
    category: "Dating",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Grindr-profil.",
    guideUrl: "https://slettmeg.no/veiledninger/slik-sletter-du-deg-fra-grindr",
  },

  // Nyheter / Medier
  {
    id: "vg",
    name: "VG",
    slug: "vg",
    category: "Nyheter",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din VG-konto.",
  },
  {
    id: "aftenposten",
    name: "Aftenposten",
    slug: "aftenposten",
    category: "Nyheter",
    difficulty: "easy",
    estimatedTime: "Umiddelbart",
    description: "Slett din Aftenposten-konto.",
  },
];

export const categories = [
  "Alle",
  "Sosiale medier",
  "Dating",
  "Teknologi",
  "Streaming",
  "Blogging",
  "Gaming",
  "Meldingstjenester",
  "E-handel",
  "Finans",
  "Skytjenester",
  "Transport",
  "Matlevering",
  "Jobbtjenester",
  "Nyheter",
  "Sokemotorer",
  "Nummeropplysning",
  "Andre",
];

export function getPlatformsByCategory(category: string): Platform[] {
  if (category === "Alle") return platforms;
  return platforms.filter((p) => p.category === category);
}

export function searchPlatforms(query: string): Platform[] {
  const lowerQuery = query.toLowerCase();
  return platforms.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.description.toLowerCase().includes(lowerQuery)
  );
}
